{% set version = "2.4.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-withr
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/withr_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/withr/withr_{{ version }}.tar.gz
  sha256: ede4cdc7e4d17e0ad24afc9fb940cba46fac4421d3a39281e9918377d73714f8

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('withr')"           # [not win]
    - "\"%R%\" -e \"library('withr')\""  # [win]

about:
  home: http://withr.r-lib.org, http://github.com/r-lib/withr#readme
  license: GPL-2.0-or-later
  summary: A set of functions to run code 'with' safely and temporarily modified global state. Many of these functions were originally a part of the 'devtools' package, this provides a simple package with limited dependencies to provide access to these functions.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r
    - croth1

# Package: withr
# Title: Run Code 'With' Temporarily Modified Global State
# Version: 2.2.0
# Authors@R: c(person(given = "Jim", family = "Hester", role = c("aut", "cre"), email = "james.f.hester@gmail.com"), person(given = "Kirill", family = "Muller", role = "aut", email = "krlmlr+r@mailbox.org"), person(given = "Kevin", family = "Ushey", role = "aut", email = "kevinushey@gmail.com"), person(given = "Hadley", family = "Wickham", role = "aut", email = "hadley@rstudio.com"), person(given = "Winston", family = "Chang", role = "aut"), person(given = "Richard", family = "Cotton", role = "ctb"), person(given = "RStudio", role = "cph"))
# Description: A set of functions to run code 'with' safely and temporarily modified global state. Many of these functions were originally a part of the 'devtools' package, this provides a simple package with limited dependencies to provide access to these functions.
# License: GPL (>= 2)
# URL: http://withr.r-lib.org, http://github.com/r-lib/withr#readme
# BugReports: http://github.com/r-lib/withr/issues
# Depends: R (>= 3.2.0)
# Imports: graphics, grDevices, stats
# Suggests: covr, DBI, knitr, lattice, methods, rmarkdown, RSQLite, testthat (>= 2.1.0)
# VignetteBuilder: knitr
# Encoding: UTF-8
# LazyData: true
# RoxygenNote: 7.1.0
# Collate: 'local_.R' 'with_.R' 'collate.R' 'connection.R' 'db.R' 'defer.R' 'wrap.R' 'devices.R' 'dir.R' 'env.R' 'file.R' 'libpaths.R' 'locale.R' 'makevars.R' 'namespace.R' 'options.R' 'par.R' 'path.R' 'rng.R' 'seed.R' 'sink.R' 'tempfile.R' 'timezone.R' 'torture.R' 'utils.R' 'with.R'
# NeedsCompilation: no
# Packaged: 2020-04-20 21:18:04 UTC; jhester
# Author: Jim Hester [aut, cre], Kirill Muller [aut], Kevin Ushey [aut], Hadley Wickham [aut], Winston Chang [aut], Richard Cotton [ctb], RStudio [cph]
# Maintainer: Jim Hester <james.f.hester@gmail.com>
# Repository: CRAN
# Date/Publication: 2020-04-20 22:10:02 UTC
